### ISSUE TITLE
mergeutility doesn't preserve page break

### ISSUE THREAD

**Issue by wpsaputra** [hvshah1974/mergeutility#1]
Hi @hvshah1974, this is  a nice script overall, however if i'm not mistaken page break from docs template doesn't preserved in output docs, do you have any suggested solution? thanks..

**Comment by hvshah1974** [comment]
Hi @wpsaputra , thank you for the feedback. In order for me to debug, could you please let me know if you're trying to use the script for a "form letter" or for labels? Thanks

**Comment by wpsaputra** [comment]
@hvshah1974 , I encounter the bug in script for "form letter", I tried to recreate the google docs template from scratch too, but no luck

**Comment by wpsaputra** [comment]
After recheck your latest commit and rerun. It seems to work fine now.. Thank you @hvshah1974
